name: iban_form_field
description: An IBAN form which deals with spacing and country specific rules.
version: 0.3.0
author: Harm Aarts <harm@aarts.email>
homepage: https://github.com/haarts/iban_form_field

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  iban: ^1.0.1
  flutter:
    sdk: flutter
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.21.1
  flutter_test:
    sdk: flutter

